# docker-compose version
version: "3.9"

# Define our containers
services:
  # MySQL
  db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=university
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MYSQL_USER=uberflip
      - MYSQL_PASSWORD=pass123
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1.schema.sql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - local

  # Adminer
  dba:
    depends_on: 
      - db
    image: adminer:4
    ports:
      - 8033:8080
    networks:
      - local

  # NGINX
  web:
    build: .
    image: nginx:1-alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/templates/default.conf.template
      - './university:/var/www/html'
    environment:
      - NGINX_HOST=${GITPOD_WORKSPACE_URL}
      - NGINX_PORT=80
    ports:
      - 8080:80
    networks:
      - local
    
  php:
    image: php:fpm-alpine
    networks:
      - local
    volumes:
      - ./university:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini

# Define networking
networks:
  local:
    external: true

  